---
parameters:
    assimtech_money.accountant.class: Assimtech\Money\Accountant


services:
    assimtech_money.accountant:
        class: "%assimtech_money.accountant.class%"

    assimtech_money.twig.accountant:
        class: Assimtech\Money\Twig\Extension\Accountant
        arguments:
            - "@assimtech_money.accountant"
        tags:
            - { name: twig.extension }
